---
name: Statistics-Zed
version: 0.03
author:
  - 'Roderick Garton <rgarton@cpan.org>'
abstract: 'Basic ztest/zscore, with optional continuity correction'
license: perl
resources:
  license: http://dev.perl.org/licenses/
build_requires:
  Math::Cephes: 0.44
  Statistics::Descriptive: 2.6
  Statistics::Distributions: 1.02
  String::Util: 0.11
  Test::More: 0
configure_requires:
  Module::Build: 0.340201
provides:
  Statistics::Zed:
    file: lib/Statistics/Zed.pm
    version: 0.03
generated_by: Module::Build version 0.340201
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
