---
abstract: 'Data-handling and calculations for ratio of observed to standard deviation (zscore)'
author:
  - 'Roderick Garton <rgarton@cpan.org>'
build_requires:
  Test::More: 0.92
configure_requires:
  Module::Build: 0.4007
dynamic_config: 1
generated_by: 'Module::Build version 0.4007, CPAN::Meta::Converter version 2.133380'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Statistics-Zed
provides:
  Statistics::Zed:
    file: lib/Statistics/Zed.pm
    version: 0.10
requires:
  Math::Cephes: 0.5303
  Scalar::Util: 1.35
  Statistics::Data: 0.08
  Statistics::Lite: 3.2
  String::Util: 1.21
resources:
  license: http://dev.perl.org/licenses/
version: 0.10
